blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/foXaCe/cryptoinfo
    about: Read the documentation before opening an issue
  - name: Home Assistant Community
    url: https://community.home-assistant.io/
    about: Ask questions and discuss with the Home Assistant community
